export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as Features } from './Features'
export { default as Works } from './Works'
export { default as Testimonials } from './Testimonials'
export { default as Clients } from './Clients'
